# Copyright 2020 The DataWorkbench Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

FROM alpine:3.12
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --update ca-certificates && update-ca-certificates

RUN mkdir -p /dataworkbench/conf
COPY ./apiserver/config/config.yaml /dataworkbench/conf/apiserver.yaml
COPY ./spacemanager/config/config.yaml /dataworkbench/conf/spacemanager.yaml
COPY ./flowmanager/config/config.yaml /dataworkbench/conf/flowmanager.yaml
COPY ./scheduler/config/config.yaml /dataworkbench/conf/scheduler.yaml

COPY ./sourcemanager/config/config.yaml /dataworkbench/conf/sourcemanager.yaml
COPY ./udfmanager/config/config.yaml /dataworkbench/conf/udfmanager.yaml
COPY ./zeppelinscale/config/config.yaml /dataworkbench/conf/zeppelinscale.yaml
COPY ./jobmanager/config/config.yaml /dataworkbench/conf/jobmanager.yaml
COPY ./jobwatcher/config/config.yaml /dataworkbench/conf/jobwatcher.yaml
COPY ./jobdeveloper/config/config.yaml /dataworkbench/conf/jobdeveloper.yaml
COPY ./notifier/config/config.yaml /dataworkbench/conf/notifier.yaml

COPY ./deploy/tmp/bin/* /usr/local/bin/

CMD ["sh"]
