# Copyright 2020 The DataWorkbench Authors. All rights reserved.
# Use of this source code is governed by a Apache license
# that can be found in the LICENSE file.

FROM alpine:3.12
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --update ca-certificates && update-ca-certificates

ENV DATAWORKBENCH_CONF=/etc/dataworkbench
RUN mkdir -p ${DATAWORKBENCH_CONF}
COPY ./apiproxy/config/config.yaml ${DATAWORKBENCH_CONF}/apiproxy.yaml
COPY ./apiserver/config/config.yaml ${DATAWORKBENCH_CONF}/apiserver.yaml
COPY ./spacemanager/config/config.yaml ${DATAWORKBENCH_CONF}/spacemanager.yaml
COPY ./flowmanager/config/config.yaml ${DATAWORKBENCH_CONF}/flowmanager.yaml
COPY ./scheduler/config/config.yaml ${DATAWORKBENCH_CONF}/scheduler.yaml

COPY ./sourcemanager/config/config.yaml ${DATAWORKBENCH_CONF}/sourcemanager.yaml
COPY ./udfmanager/config/config.yaml ${DATAWORKBENCH_CONF}/udfmanager.yaml
COPY ./zeppelinscale/config/config.yaml ${DATAWORKBENCH_CONF}/zeppelinscale.yaml
COPY ./jobmanager/config/config.yaml ${DATAWORKBENCH_CONF}/jobmanager.yaml
COPY ./jobwatcher/config/config.yaml ${DATAWORKBENCH_CONF}/jobwatcher.yaml
COPY ./jobdeveloper/config/config.yaml ${DATAWORKBENCH_CONF}/jobdeveloper.yaml
COPY ./notifier/config/config.yaml ${DATAWORKBENCH_CONF}/notifier.yaml

#RUN find ./deploy/tmp/bin/ -type f -exec upx {} \;
COPY ./deploy/tmp/bin /usr/local/bin/

CMD ["sh"]
