apiVersion: v1
kind: Service
metadata:
  name: {{ include "databench.fullname" . }}-apiglobal
  labels:
{{ include "databench.labels" . | indent 4 }}
    component: apiglobal-service
spec:
  type: ClusterIP
  ports:
    - name: service
      port: {{ .Values.ports.apiGlobal }}
      targetPort: service
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: apiglobal
