apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "databench.fullname" . }}-enginemanager
  labels:
{{ include "databench.labels" . | indent 4 }}
    component: enginemanager
annotations:
  {{- range $key, $value := .Values.enginemanager.annotations }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ coalesce .Values.enginemanager.replicas .Values.common.replicas }}
  strategy:
    type: {{ coalesce .Values.enginemanager.strategy .Values.common.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: enginemanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: enginemanager
      annotations:
      {{- range $key, $value := .Values.enginemanager.podAnnotations }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Release.Name }}-engine-manager
      initContainers:
      - name: wait-mysql
        image: {{ .Values.image.busybox }}
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', '{{ include "mysql.waiting.cmd" . }}']
      containers:
      - name: enginemanager
        image: {{ .Values.image.repo }}/enginemanager:{{- .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "enginemanager start -c ${DATABENCH_CONF}/common-config.yaml"]
        ports:
          - name: service
            containerPort: {{ .Values.ports.enginemanager }}
          - name: metrics
            containerPort: {{ .Values.metricsPorts.enginemanager }}
        env:
          - name: ENGINE_MANAGER_GRPC_SERVER_ADDRESS
            value: "0.0.0.0:{{- .Values.ports.enginemanager }}"
          - name: ENGINE_MANAGER_METRICS_SERVER_ADDRESS
            value: "0.0.0.0:{{- .Values.metricsPorts.enginemanager }}"
          - name: ENGINE_MANAGER_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mysql.secretName }}
                key: root
          - name: ENGINE_MANAGER_IAAS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: databench-secret
                key: access_key_id
          - name: ENGINE_MANAGER_IAAS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: databench-secret
                key: secret_access_key
          - name: ENGINE_MANAGER_FLINK_DOMAIN
            value: {{ .Values.domain | quote }}
          - name: ENGINE_MANAGER_FLINK_HDFS_CONFIGMAP_NAME
            value: {{ .Values.hdfs.configmapName }}
          - name: ENGINE_MANAGER_FLINK_HDFS_CONFIGMAP_NAMESPACE
            value: {{ .Release.Namespace | quote }}
          {{- range $ename, $evalue := .Values.enginemanager.envs }}
          - name: {{ $ename }}
            value: {{ $evalue | quote }}
          {{- end }}
        volumeMounts:
          - name: databench-config
            mountPath: "/etc/dataworkbench"
            readOnly: true
         {{- if .Values.enginemanager.envs.ENGINE_MANAGER_KUBE_CONF_PATH }}
          - name: kube-config-volume
            mountPath: {{ .Values.enginemanager.envs.ENGINE_MANAGER_KUBE_CONF_PATH }}
            readOnly: true
        {{- end }}
          - name: helm-repo-volume
            mountPath: {{ .Values.enginemanager.envs.ENGINE_MANAGER_HELM_REPOSITORY_CACHE }}
            readOnly: true
        readinessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:{{ .Values.ports.enginemanager }}"]
          {{- if .Values.enginemanager.readinessProbe }}
          periodSeconds: {{ .Values.enginemanager.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.enginemanager.readinessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.readinessProbe.initialDelaySeconds }}
          {{- end }}
        livenessProbe:
          exec:
            command: [ "grpc_health_probe", "-addr=:{{ .Values.ports.enginemanager }}" ]
          {{- if .Values.enginemanager.livenessProbe }}
          periodSeconds: {{ .Values.enginemanager.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.enginemanager.livenessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.livenessProbe.initialDelaySeconds }}
          {{- end }}
      volumes:
        - name: databench-config
          configMap:
            name: databench-config
            items:
              - key: "config.yaml"
                path: "common-config.yaml"
        {{- if .Values.enginemanager.envs.ENGINE_MANAGER_KUBE_CONF_PATH }}
        - name: kube-config-volume
          hostPath:
            path: {{ .Values.enginemanager.kubeConfigPath }}
            type: File
        {{- end }}
        - name: helm-repo-volume
          hostPath:
            path: {{ .Values.enginemanager.helmRepoPath }}
            type: Directory
