apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-engine-manager
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    app: "databench"
    release: {{ .Release.Name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-engine-manager
rules:
- apiGroups: ["", "extensions", "networking.k8s.io", "apps"]
  resources: ["ingresses", "configmaps", "namespaces", "secrets", "services", "deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-engine-manager
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-engine-manager
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Release.Name }}-engine-manager
  apiGroup: rbac.authorization.k8s.io
