apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "databench.fullname" . }}-notifier
  labels:
{{ include "databench.labels" . | indent 4 }}
    component: notifier
annotations:
  {{- range $key, $value := .Values.notifier.annotations }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ coalesce .Values.notifier.replicas .Values.common.replicas }}
  strategy:
    type: {{ coalesce .Values.notifier.strategy .Values.common.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: notifier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: notifier
      annotations:
      {{- range $key, $value := .Values.notifier.podAnnotations }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', '{{ include "mysql.waiting.cmd" . }}']
      containers:
      - name: notifier
        image: {{ .Values.image.repo }}/notifier:{{ .Values.image.repo }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "notifier start -c ${DATABENCH_CONF}/common-config.yaml"]
        ports:
          - name: service
            containerPort: {{ .Values.ports.notifier }}
          - name: metrics
            containerPort: {{ .Values.metricsPorts.notifier }}
        env:
          - name: NOTIFIER_GRPC_SERVER_ADDRESS
            value: "0.0.0.0:{{- .Values.ports.notifier }}"
          - name: NOTIFIER_METRICS_SERVER_ADDRESS
            value: "0.0.0.0:{{- .Values.metricsPorts.notifier }}"
          - name: NOTIFIER_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mysql.secretName }}
                key: root
          {{- range $ename, $evalue := .Values.notifier.envs }}
          - name: {{ $ename }}
            value: {{ $evalue | quote }}
          {{- end }}
        volumeMounts:
          - name: config
            mountPath: "/etc/dataworkbench"
            readOnly: true
        readinessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:{{ .Values.ports.notifier }}"]
          {{- if .Values.notifier.readinessProbe }}
          periodSeconds: {{ .Values.notifier.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.notifier.readinessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.readinessProbe.initialDelaySeconds }}
          {{- end }}
        livenessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:{{ .Values.ports.notifier }}"]
          {{- if .Values.notifier.livenessProbe }}
          periodSeconds: {{ .Values.notifier.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.notifier.livenessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.livenessProbe.initialDelaySeconds }}
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: databench-config
            items:
              - key: "config.yaml"
                path: "common-config.yaml"
