apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "databench.fullname" . }}-scheduler
  labels:
{{ include "databench.labels" . | indent 4 }}
    component: scheduler
annotations:
  {{- range $key, $value := .Values.scheduler.annotations }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ coalesce .Values.scheduler.replicas .Values.common.replicas }}
  strategy:
    type: {{ coalesce .Values.scheduler.strategy .Values.common.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: scheduler
      annotations:
      {{- range $key, $value := .Values.scheduler.podAnnotations }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', '{{ include "mysql.waiting.cmd" . }}']
      - name: wait-etcd
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', '{{ include "etcd.waiting.cmd" . }}']
      containers:
      - name: scheduler
        image: {{ .Values.image.repo }}/scheduler:{{ .Values.image.repo }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "scheduler start -c ${DATABENCH_CONF}/common-config.yaml"]
        ports:
          - name: service
            containerPort: {{ .Values.ports.scheduler }}
          - name: metrics
            containerPort: {{ .Values.metricsPorts.scheduler }}
        env:
          - name: SCHEDULER_GRPC_SERVER_ADDRESS
            value: "0.0.0.0:{{- .Values.ports.scheduler }}"
          - name: SCHEDULER_METRICS_SERVER_ADDRESS
            value: "0.0.0.0:{{- .Values.metricsPorts.scheduler }}"
          - name: SCHEDULER_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mysql.secretName }}
                key: root
{{ include "scheduler.link.services" . | indent 10 }}
          {{- range $ename, $evalue := .Values.scheduler.envs }}
          - name: {{ $ename }}
            value: {{ $evalue | quote }}
          {{- end }}
        readinessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:{{ .Values.ports.scheduler }}"]
          {{- if .Values.scheduler.readinessProbe }}
          periodSeconds: {{ .Values.scheduler.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.scheduler.readinessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.readinessProbe.initialDelaySeconds }}
          {{- end }}
        livenessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:{{ .Values.ports.scheduler }}"]
          {{- if .Values.scheduler.livenessProbe }}
          periodSeconds: {{ .Values.scheduler.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.scheduler.livenessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.livenessProbe.initialDelaySeconds }}
          {{- end }}
        volumeMounts:
          - name: config
            mountPath: "/etc/dataworkbench"
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: databench-config
            items:
              - key: "config.yaml"
                path: "common-config.yaml"
