{{- if .Values.serviceMonitor.enabled }}
{{- range $component, $_ := .Values.metricsPorts }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $component }}-servicemonitor
  labels:
    {{- toYaml $.Values.serviceMonitor.defaults.labels | nindent 4 }}
    componet: {{ $component }}-servicemonitor
  namespace: {{ $.Values.serviceMonitor.namespace }}
spec:
  jobLabel: {{ $component }}-exporter
  selector:
    matchLabels:
      component: {{ $component }}-service
  namespaceSelector:
    any: true
  endpoints:
  - port: {{ $.Values.serviceMonitor.port }}
    interval: {{ $.Values.serviceMonitor.interval }}
    honorLabels: true
{{- end }}
{{- end }}

