apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "databench.fullname" . }}-apiglobal
  labels:
{{ include "dataworkbench.labels" . | indent 4 }}
    component: apiglobal
annotations:
  {{- range $key, $value := .Values.apiglobal.annotations }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ coalesce .Values.common.replicas .Values.apiglobal.replicas }}
  strategy:
    type: {{ coalesce .Values.common.strategy .Values.apiglobal.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: apiglobal
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: apiglobal
      annotations:
      {{- range $key, $value := .Values.apiglobal.podAnnotations }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    spec:
      containers:
        - name: apiglobal
          image: {{ .Values.image.dataworkbench | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c", "apiglobal start -c ${DATABENCH_CONF}/apiglobal.yaml"]
          ports:
            - containerPort: {{ .Values.ports.apiGlobal }}
              name: service
          env:
            - name: API_GLOBAL_LOG_LEVEL
              value: {{ coalesce .Values.apiglobal.logLevel .Values.common.logLevel | quote }}
            - name: API_GLOBAL_HTTP_SERVER_ADDRESS
              value: "0.0.0.0:{{ .Values.ports.apiGlobal }}"
            - name: API_GLOBAL_TRACER_LOCAL_AGENT
              value: '{{ include "service.jaeger" . }}'
            {{- range $ename, $evalue := .Values.apiglobal.envs }}
            - name: {{ $ename }}
              value: {{ $evalue | quote }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: service
            {{- if .Values.apiglobal.readinessProbe }}
            periodSeconds: {{ .Values.apiglobal.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.apiglobal.readinessProbe.initialDelaySeconds }}
            {{- else }}
            periodSeconds: {{ .Values.common.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.common.readinessProbe.initialDelaySeconds }}
            {{- end }}
          livenessProbe:
            tcpSocket:
              port: service
            {{- if .Values.apiglobal.livenessProbe }}
            initialDelaySeconds: {{ .Values.apiglobal.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.apiglobal.livenessProbe.periodSeconds }}
            {{- else }}
            periodSeconds: {{ .Values.common.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.common.livenessProbe.initialDelaySeconds }}
            {{- end }}
