apiVersion: v1
kind: Service
metadata:
  name: {{ include "databench.fullname" . }}-apiglobal
  labels:
{{ include "dataworkbench.labels" . | indent 4 }}
    component: apiglobal-service
  annotations:
    {{ toYaml .Values.apiglobal.service.annotations | indent 4 }}
spec:
  type: {{ .Values.apiglobal.service.type }}
  ports:
    - name: service
      port: {{ .Values.ports.apiglobal }}
      targetPort: service
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: apiglobal
