apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "databench.fullname" . }}-db-init-job
  labels:
{{ include "dataworkbench.labels" . | indent 4 }}
    component: db-init-job
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: db-init-job
    spec:
      initContainers:
        - name: wait-mysql
          image: busybox:1.28.4
          imagePullPolicy: IfNotPresent
          command:
            - 'sh'
            - '-c'
            - '{{ include "mysql.waiting.cmd" . }}'
      containers:
        - name: db-init-job
          image: {{ .Values.image.flyway }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - "/flyway/sql/ddl/ddl_init.sh"
            - '-h{{ include "mysql.host" . }}'
            - "-uroot"
            - "--connect-timeout=5"
          env:
            - name: PASSWORD
              value: {{ include "mysql.root.password" . | quote }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30