apiVersion: v1
kind: Service
metadata:
  name: {{ include "databench.fullname" . }}-jaeger
  labels:
{{ include "databench.labels" . | indent 4 }}
    component: jaeger-service
spec:
  {{- if .Values.jaeger.service }}
  type: {{ coalesce .Values.jaeger.service.type .Values.common.service.type }}
  {{- else }}
  type: {{ .Values.common.service.type }}
  {{- end }}
  ports:
    - name: service
      port: {{ .Values.ports.jaeger }}
      targetPort: service
      protocol: TCP
    - name: web
      port: {{ .Values.ports.jaegerWeb }}
      targetPort: web
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: jaeger