apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jobwatcher
  labels:
{{ include "dataworkbench.labels" . | indent 4 }}
    component: jobwatcher
annotations:
  {{- range $key, $value := .Values.jobwatcher.annotations }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ coalesce .Values.common.replicas .Values.jobwatcher.replicas }}
  strategy:
    type: {{ coalesce .Values.common.strategy .Values.jobwatcher.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: jobwatcher
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: jobwatcher
      annotations:
      {{- range $key, $value := .Values.jobwatcher.podAnnotations }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', '{{ include "mysql.waiting.cmd" . }}']
      containers:
      - name: jobwatcher
        image: {{ .Values.image.dataworkbench | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "jobwatcher start -c ${DATABENCH_CONF}/jobwatcher.yaml"]
        ports:
          - containerPort: {{ .Values.ports.jobwatcher }}
            name: service
          - containerPort: {{ .Values.ports.jaeger }}
            name: jaeger
        env:
          - name: JOB_WATCHER_LOG_LEVEL
            value: {{ coalesce .Values.jobwatcher.logLevel .Values.common.logLevel | quote }}
          - name: JOB_WATCHER_GRPC_SERVER_ADDRESS
            value: "0.0.0.0:{{- .Values.ports.jobwatcher }}"
          - name: JOB_WATCHER_GRPC_SERVER_LOG_LEVEL
            value: {{ coalesce .Values.jobwatcher.grpcLogLevel .Values.common.grpcLogLevel | quote }}
          - name: JOB_WATCHER_GRPC_SERVER_LOG_VERBOSITY
            value: {{ coalesce .Values.jobwatcher.grpcLogVerbosity .Values.common.grpcLogVerbosity | quote }}
          - name: JOB_WATCHER_JOBDEVELOPER_SERVER_ADDRESS
            value: {{ include "service.jobdeveloper" . | quote }}
          - name: JOB_WATCHER_TRACER_LOCAL_AGENT
            value: '{{ include "service.jaeger" . }}'
          - name: JOB_WATCHER_MYSQL_HOSTS
            value: '{{- include "mysql.hostPort" . }}'
          - name: JOB_WATCHER_MYSQL_PASSWORD
            value: {{ include "mysql.root.password" . | quote }}
          - name: JOB_WATCHER_METRICS_ENABLED
          {{- if .Values.jobwatcher.metric.enabled }}
            value: "true"
          - name: JOB_WATCHER_METRICS_SERVER_ADDRESS
            value: {{ .Values.jobwatcher.metric.address }}
          {{- else }}
            value: "false"
          {{- end }}
          {{- range $ename, $evalue := .Values.jobwatcher.envs }}
          - name: {{ $ename }}
            value: {{ $evalue | quote }}
          {{- end }}
        readinessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:{{ .Values.ports.jobwatcher }}"]
          {{- if .Values.jobwatcher.readinessProbe }}
          periodSeconds: {{ .Values.jobwatcher.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.jobwatcher.readinessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.readinessProbe.initialDelaySeconds }}
          {{- end }}
        livenessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:{{ .Values.ports.jobwatcher }}"]
          {{- if .Values.jobwatcher.livenessProbe }}
          periodSeconds: {{ .Values.jobwatcher.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.jobwatcher.livenessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.livenessProbe.initialDelaySeconds }}
          {{- end }}
