apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-spacemanager
  labels:
{{ include "dataworkbench.labels" . | indent 4 }}
    component: spacemanager
annotations:
  {{- range $key, $value := .Values.spacemanager.annotations }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ coalesce .Values.common.replicas .Values.spacemanager.replicas }}
  strategy:
    type: {{ coalesce .Values.common.strategy .Values.spacemanager.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: spacemanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: spacemanager
      annotations:
      {{- range $key, $value := .Values.spacemanager.podAnnotations }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    spec:
      initContainers:
      - name: wait-mysql
        image: busybox:1.28.4
        imagePullPolicy: IfNotPresent
        command:
          - '/bin/sh'
          - '-c'
          - '{{ include "mysql.waiting.cmd" . }}'
      containers:
      - name: spacemanager
        image: {{ .Values.image.dataworkbench | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
          - "sh"
          - "-c"
          - "spacemanager start -c /dataworkbench/conf/spacemanager.yaml"
        ports:
          - containerPort: {{ .Values.ports.spacemanager }}
            name: service
          - containerPort: {{ .Values.ports.opentracing }}
            name: opentracing
        env:
          - name: SPACE_MANAGER_LOG_LEVEL
            value: {{ coalesce .Values.spacemanager.logLevel .Values.common.logLevel | quote }}
          - name: SPACE_MANAGER_GRPC_SERVER_ADDRESS
            value: "0.0.0.0:{{- .Values.ports.spacemanager }}"
          - name: SPACE_MANAGER_GRPC_SERVER_LOG_LEVEL
            value: { { coalesce .Values.spacemanager.grpcLogLevel .Values.common.grpcLogLevel | quote } }
          - name: SPACE_MANAGER_GRPC_SERVER_LOG_VERBOSITY
            value: { { coalesce .Values.spacemanager.grpcLogVerbosity .Values.common.grpcLogVerbosity | quote } }
          - name: SPACE_MANAGER_TRACER_LOCAL_AGENT
            value: "0.0.0.0:{{- .Values.ports.opentracing }}"
          - name: SPACE_MANAGER_MYSQL_HOSTS
            value: '{{- include "mysql.host" . }}:{{- include "mysql.port" . }}'
          - name: SPACE_MANAGER_MYSQL_PASSWORD
            value: {{ include "mysql.root.password" . | quote }}
          - name: SPACE_MANAGER_METRICS_SERVER_ENABLED
          {{- if .Values.spacemanager.metric.enabled }}
            value: "true"
          - name: SPACE_MANAGER_METRICS_SERVER_ADDRESS
            value: {{ .Values.spacemanager.metric.address }}
          - name: SPACE_MANAGER_METRICS_SERVER_URL_PATH
            value: {{ .Values.spacemanager.metric.urlPath }}
          {{- else }}
            value: "false"
          {{- end }}
          {{- range $ename, $evalue := .Values.spacemanager.envs }}
          - name: {{ $ename }}
            value: {{ $evalue | quote }}
          {{- end }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.ports.spacemanager }}
          {{- if .Values.spacemanager.readinessProbe }}
          periodSeconds: {{ .Values.spacemanager.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.spacemanager.readinessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.readinessProbe.initialDelaySeconds }}
          {{- end }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.ports.spacemanager }}
          {{- if .Values.spacemanager.livenessProbe }}
          periodSeconds: {{ .Values.spacemanager.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.spacemanager.livenessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.livenessProbe.initialDelaySeconds }}
          {{- end }}
