{{- if .Values.zeppelin.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zeppelin
  labels:
{{ include "dataworkbench.labels" . | indent 4 }}
    component: zeppelin
  annotations:
    {{ toYaml .Values.zeppelin.service.annotations | indent 4 }}
spec:
  type: {{ .Values.zeppelin.service.type }}
  ports:
    - name: service
      port: {{ .Values.ports.zeppelin }}
      targetPort: service
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: zeppelin
{{- end }}