---
redisCluster:
  clusterSize: 3
  image: quay.io/opstree/redis
  tag: v6.2.5
  imagePullPolicy: IfNotPresent
  # redisSecret:
  #   secretName: redis-secret
  #   secretKey: password
  leader:
    replicas: 3
    serviceType: ClusterIP
    affinity: {}
  follower:
    replicas: 3
    serviceType: ClusterIP
    affinity: {}
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

storageSpec:
  enable: true
  size: 10Gi
  accessModes: ["ReadWriteOnce"]
  localPv:
    enable: true # if use local pv with hostPath
    home: /data/dataomnis
    reclaimPolicy: Retain
    nodes: # the length of nodes must be equal to clusterSize
      - worker-s001
      - worker-s002
      - worker-s003

redisExporter:
  enabled: false
  image: quay.io/opstree/redis-exporter
  tag: "1.0"
  imagePullPolicy: IfNotPresent
  resources: {}
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
    # limits:
    #   cpu: 100m
    #   memory: 128Mi

sidecars: []
  # - name: "sidecar1"
  #   image: "image:1.0"
  #   imagePullPolicy: Always
  #   resources:
  #     limits:
  #       cpu: 50m
  #       memory: 64Mi
  #     requests:
  #       cpu: 10m
  #       memory: 32M
  #   env:
  #   - name: VAR_NAME
  #     value: "value1"

# priorityClassName: "-"

nodeSelector: {}
  # memory: medium

securityContext: {}
  # runAsUser: 1000

affinity: {}
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: disktype
  #         operator: In
  #         values:
  #         - ssd

#externalService:
#  enabled: false
#  # annotations:
#  #   foo: bar
#  serviceType: LoadBalancer
#  port: 6379
#
#serviceMonitor:
#  enabled: false
#  interval: 30s
#  scrapeTimeout: 10s
#  namespace: monitoring