# Default values for etcd-cluster.

replicaCount: 3

resources:
   limits:
     cpu: 1000m
     memory: 2048Mi
   requests:
     cpu: 100m
     memory: 128Mi

persistent:
  size: 5Gi
  accessModes: ["ReadWriteOnce"]
