podAnnotations: {}

image:
  regitry: quay.io
  pullPolicy: IfNotPresent
  pullSecrets: []
  operator: spotahome/redis-operator:v1.0.0

resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 50Mi
rbac:
  install: true
  apiVersion: v1
monitoring:
  enabled: false
  serviceMonitor: false
  serviceAnnotations: {}
  prometheus:
    name: unknown