imageRegitry: quay.io
image: spotahome/redis-operator
tag: v1.0.0
pullPolicy: IfNotPresent
podAnnotations: {}
resources:
  requests:
    cpu: 10m
    memory: 50Mi
  limits:
    cpu: 100m
    memory: 50Mi
rbac:
  install: true
  apiVersion: v1
  imagePullSecrets: []
monitoring:
  enabled: false
  serviceMonitor: false
  serviceAnnotations: {}
  prometheus:
    name: unknown