apiVersion: qy.dataworkbench.com/v1
kind: HDFS
metadata:
  name: {{ .Release.Name }}
spec:
  version: {{ .Chart.AppVersion }}  # hadoop version
  image: {{ .Values.image.registry }}/{{ .Values.image.hadoop }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  namenode:
    name: namenode
    storageClass: {{ include "hdfs.fullname" . }}-namenode-sc
    capacity: 10Gi
    replicas: 2
  journalnode:
    name: journalnode
    storageClass: {{ include "hdfs.fullname" . }}-journalnode-sc
    capacity: 10Gi
    replicas: {{ include "journalnode.length" . }}
  datanode:
    name: datanode
    storageClass: {{ include "hdfs.fullname" . }}-datanode-sc
    capacity: 10Gi
    datadirs:
      - dn1    #  k8s节点多目录
      - dn2
    replicas: {{ include "datanode.length" . }}
  zkQuorum: {{ include "zookeeper.quorum" . }}
  hdfsSite:
    - property: "dfs.namenode.handler.count"
      value: "10"
    - property: "dfs.replication"
      value: "2"
{{- if .Values.yarn.nmReplicas }}
  yarn:
    name: yarn
    rmReplicas: 1
    nmReplicas: {{ .Values.yarn.nmReplicas }}
{{- end }}