apiVersion: v1
kind: ConfigMap
metadata:
  name: dataomnis-logbackup-config
  labels:
{{ include "logbackup.labels" . | indent 4 }}
data:
  config.yaml: |
    log:
      level: {{ .Values.logConfig.level }}
      output: file
      file:
        path: "{{ .Values.logConfig.containerPath }}/logbackup/logbackup.log"
        max_size: {{ .Values.logConfig.maxSize }}

    root_log_dir_path: {{ .Values.logConfig.containerPath }}
    zone: {{ .Values.logConfig.zone }}
    bucket_name: {{ .Values.logConfig.bucketName }}
