apiVersion: v1
kind: Secret
metadata:
  name: logbackup-secret
  labels: {{- include "logbackup.labels" . | nindent 4 }}
data:
  access_key_id: {{ .Values.logConfig.access_key_id | b64enc }}
  secret_access_key: {{ .Values.logConfig.secret_access_key | b64enc }}