# Default values for mysql-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
pullPolicy: IfNotPresent
image: percona/percona-xtradb-cluster-operator:1.5.0
containerPort: 60000