apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.pmmclientname1 }}
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/component: pxc
      app.kubernetes.io/instance: {{ .Values.mysqlclustername }}-pxc-db
#      app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
      app.kubernetes.io/name: percona-xtradb-cluster
      app.kubernetes.io/part-of: percona-xtradb-cluster
  serviceName: {{ .Values.pmmclientname1 }}
  template:
    metadata:
#      annotations:
#        percona.com/configuration-hash: e9c6505d42d0378e0c0e64c88088f6a6
#      creationTimestamp: null
      labels:
        app.kubernetes.io/component: pxc
        app.kubernetes.io/instance: {{ .Values.mysqlclustername }}-pxc-db
#        app.kubernetes.io/managed-by: percona-xtradb-cluster-operator
        app.kubernetes.io/name: percona-xtradb-cluster
        app.kubernetes.io/part-of: percona-xtradb-cluster
    spec:
      containers:
        - env:
            - name: PMM_SERVER
              value: {{ .Values.mysqlmonitorservice }}
            - name: PMM_USER
              value: admin
            - name: PMM_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pmmserver
                  name: internal-{{ .Values.mysqlclustername }}-pxc-db
            - name: CLIENT_PORT_LISTEN
              value: "7777"
            - name: CLIENT_PORT_MIN
              value: "30100"
            - name: CLIENT_PORT_MAX
              value: "30105"
            - name: POD_NAME
              value: {{ .Values.pmmclientname1 }}
            - name: POD_NAMESPASE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: PMM_AGENT_SERVER_ADDRESS
              value: {{ .Values.mysqlmonitorservice }}
            - name: PMM_AGENT_SERVER_USERNAME
              value: admin
            - name: PMM_AGENT_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: pmmserver
                  name: internal-mysql-cluster-pxc-db
            - name: PMM_AGENT_LISTEN_PORT
              value: "7777"
            - name: PMM_AGENT_PORTS_MIN
              value: "30100"
            - name: PMM_AGENT_PORTS_MAX
              value: "30105"
            - name: PMM_AGENT_CONFIG_FILE
              value: /usr/local/percona/pmm2/config/pmm-agent.yaml
            - name: PMM_AGENT_SERVER_INSECURE_TLS
              value: "1"
            - name: PMM_AGENT_LISTEN_ADDRESS
              value: 0.0.0.0
            - name: PMM_AGENT_SETUP_NODE_NAME
              value: $(POD_NAMESPASE)-$(POD_NAME)
            - name: PMM_AGENT_SETUP_METRICS_MODE
              value: push
            - name: PMM_AGENT_SETUP
              value: "1"
            - name: PMM_AGENT_SETUP_FORCE
              value: "1"
            - name: PMM_AGENT_SETUP_NODE_TYPE
              value: container
            - name: DB_TYPE
              value: mysql
            - name: DB_USER
              value: {{ .Values.mysqluser }}
            - name: DB_PASSWORD
              value: {{ .Values.mysqlpassword }}
            - name: DB_ARGS
              value: --query-source=perfschema
            - name: DB_CLUSTER
              value: pxc
            - name: DB_HOST0
              value: {{ .Values.mysqlclustername }}-pxc-db-pxc-0.{{ .Values.mysqlclustername }}-pxc-db-pxc.$(POD_NAMESPASE).svc.cluster.local
            - name: DB_HOST1
              value: {{ .Values.mysqlclustername }}-pxc-db-pxc-1.{{ .Values.mysqlclustername }}-pxc-db-pxc.$(POD_NAMESPASE).svc.cluster.local
            - name: DB_HOST2
              value: {{ .Values.mysqlclustername }}-pxc-db-pxc-2.{{ .Values.mysqlclustername }}-pxc-db-pxc.$(POD_NAMESPASE).svc.cluster.local
            - name: DB_HOST
              value: $(DB_HOST1)
            - name: DB_PORT
              value: "33062"
            - name: CLUSTER_NAME
              value: {{ .Values.mysqlclustername }}-pxc-db-pxc
            - name: PMM_ADMIN_CUSTOM_PARAMS
            - name: PMM_AGENT_PRERUN_SCRIPT
              value: |-
                pmm-admin status --wait=10s;
                pmm-admin add $(DB_TYPE) $(PMM_ADMIN_CUSTOM_PARAMS) --skip-connection-check --metrics-mode=push  --username=$(DB_USER) --password=$(DB_PASSWORD) --cluster=$(CLUSTER_NAME)  --service-name=$(PMM_AGENT_SETUP_NODE_NAME) --host=$(DB_HOST1) --port=$(DB_PORT) $(DB_ARGS);
                pmm-admin annotate --service-name=$(PMM_AGENT_SETUP_NODE_NAME) 'Service restarted'
          envFrom:
            - secretRef:
                name: {{ .Values.mysqlclustername }}-pxc-db-env-vars-pxc
                optional: true
          image: percona/pmm-client:2.18.0
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command:
                  - bash
                  - -c
                  - pmm-admin inventory remove node --force $(pmm-admin status --json
                    | python -c "import sys, json; print(json.load(sys.stdin)['pmm_agent_status']['node_id'])")
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /local/Status
              port: 7777
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 5
          name: pmm-client
          ports:
            - containerPort: 7777
              protocol: TCP
            - containerPort: 30100
              protocol: TCP
            - containerPort: 30101
              protocol: TCP
            - containerPort: 30102
              protocol: TCP
            - containerPort: 30103
              protocol: TCP
            - containerPort: 30104
              protocol: TCP
            - containerPort: 30105
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: datadir
      dnsPolicy: ClusterFirst
#      initContainers:
#        - command:
#            - /pxc-init-entrypoint.sh
#          image: percona/percona-xtradb-cluster-operator:1.9.0
#          imagePullPolicy: Always
#          name: pxc-init
#          resources:
#            requests:
#              cpu: 800m
#              memory: 1G
#          terminationMessagePath: /dev/termination-log
#          terminationMessagePolicy: File
#          volumeMounts:
#            - mountPath: /var/lib/mysql
#              name: datadir
      restartPolicy: Always
      volumes:
        - name: datadir
          hostPath:
            path: /root/testmysql
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1001
        supplementalGroups:
          - 1001
      serviceAccount: default
      serviceAccountName: default
      terminationGracePeriodSeconds: 600
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate

