apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataomnis.fullname" . }}-apiserver
  labels:
{{ include "dataomnis.labels" . | indent 4 }}
    component: apiserver
annotations:
{{- range $key, $value := .Values.apiserver.annotations }}
  {{ $key | quote }}: {{ $value | quote }}
{{- end }}
spec:
  replicas: {{ coalesce .Values.apiserver.replicas .Values.common.replicas }}
  strategy:
    type: {{ coalesce .Values.apiserver.strategy .Values.common.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: apiserver
      annotations:
      {{- range $key, $value := .Values.apiserver.podAnnotations }}
        {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: component
                    operator: In
                    values:
                      - apiserver
              topologyKey: 'kubernetes.io/hostname'
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        {{- range .Values.image.pullSecret }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      initContainers:
        - name: envsubst
          image: {{ .Values.image.registry }}/dataomnis/envsubst:latest
          args:
            - sh
            - -c
            - cat /data/filebeat.yaml | envsubst > /etc/logsidecar/filebeat.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          volumeMounts:
            - mountPath: /data
              name: filebeat-config
            - mountPath: /etc/logsidecar
              name: injected-config
      containers:
        {{- if .Values.filebeat.enabled }}
        - name: filebeat-sidecar
          image: {{ .Values.image.registry }}/dataomnis/filebeat:6.7.0
          imagePullPolicy: IfNotPresent
          args:
            - '-c'
            - /etc/logsidecar/filebeat.yaml
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
          volumeMounts:
            - name: log
              mountPath: /logs
            - name: injected-config
              mountPath: /etc/logsidecar
              readOnly: true
        {{- end }}
        - name: apiserver
          image: {{ .Values.image.registry }}/dataomnis/apiserver:{{- .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/bin/sh", "-c", "apiserver start -c /opt/dataomnis/conf/apiserver.yaml"]
          ports:
            - name: service
              containerPort: {{ .Values.ports.apiserver }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: API_SERVER_LOG_FILE_PATH
              value: /opt/dataomnis/log/$(POD_NAME).log
{{ include "apiserver.link.services" . | indent 12 }}
            {{- range $ename, $evalue := .Values.apiserver.envs }}
            - name: API_SERVER_{{ $ename }}
              value: {{ $evalue | quote }}
            {{- end }}
          readinessProbe:
            tcpSocket:
              port: service
            {{- if .Values.apiserver.readinessProbe }}
            periodSeconds: {{ .Values.apiserver.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.apiserver.readinessProbe.initialDelaySeconds }}
            {{- else }}
            periodSeconds: {{ .Values.common.readinessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.common.readinessProbe.initialDelaySeconds }}
            {{- end }}
          resources:
            {{- toYaml .Values.apiserver.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: service
            {{- if .Values.apiserver.livenessProbe }}
            initialDelaySeconds: {{ .Values.apiserver.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.apiserver.livenessProbe.periodSeconds }}
            {{- else }}
            periodSeconds: {{ .Values.common.livenessProbe.periodSeconds }}
            initialDelaySeconds: {{ .Values.common.livenessProbe.initialDelaySeconds }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /opt/dataomnis/conf
              readOnly: true
            {{- if eq .Values.common.logOutput "file" }}
            - name: log
              mountPath: /opt/dataomnis/log
            {{- end }}
      volumes:
        - name: config
          configMap:
            name: dataomnis-config
            items:
              - key: apiserver.yaml
                path: apiserver.yaml
        {{- if eq .Values.common.logOutput "file" }}
        - name: log
          hostPath:
            path: {{ .Values.persistent.hostPath }}/log/apiserver
            type: Directory
        {{- end  }}
        {{- if .Values.filebeat.enabled }}
        - name: filebeat-config
          configMap:
            name: filebeat-config
            items:
              - key: filebeat.yaml
                path: filebeat.yaml
        - name: injected-config
          emptyDir: {}
        {{- end  }}
