{{- if and (eq .Values.common.logOutput "file" ) .Values.filebeat.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yaml: |
    filebeat.inputs:
    - type: log
      enabled: true
      paths:
      - /logs/${POD_NAME}.log
    output.console:
      codec.format:
        string: '%{[log.file.path]} %{[message]}'
    logging.level: warning
{{- end }}
