apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataomnis.fullname" . }}-resourcemanager
  labels:
{{ include "dataomnis.labels" . | indent 4 }}
    component: resourcemanager
spec:
  replicas: {{ coalesce .Values.resourcemanager.replicas .Values.common.replicas }}
  strategy:
    type: {{ coalesce .Values.resourcemanager.strategy .Values.common.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: resourcemanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: resourcemanager
      annotations:
      {{- range $key, $value := .Values.resourcemanager.podAnnotations }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
      - name: wait-mysql
        image: {{ .Values.image.registry }}/library/{{- .Values.image.busybox }}
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', '{{ include "mysql.waiting.cmd" . }}']
      containers:
      {{- if .Values.filebeat.enabled }}
      - name: filebeat-sidecar
        image: {{ .Values.image.registry }}/dataomnis/filebeat:6.7.0
        imagePullPolicy: IfNotPresent
        args:
          - '-c'
          - /etc/logsidecar/filebeat.yaml
        env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
        volumeMounts:
          - name: log
            mountPath: /logs
          - name: filebeat-config
            mountPath: /etc/logsidecar
            readOnly: true
      {{- end }}
      - name: resourcemanager
        image: {{ .Values.image.registry }}/dataomnis/resourcemanager:{{- .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "resourcemanager start -c /opt/dataomnis/conf/resourcemanager.yaml"]
        ports:
          - name: service
            containerPort: {{ .Values.ports.resourcemanager }}
          - name: metrics
            containerPort: {{ .Values.metricsPorts.resourcemanager }}
        env:
          - name: RESOURCE_MANAGER_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mysql.secretName }}
                key: root
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: RESOURCE_MANAGER_LOG_FILE_PATH
            value: "/opt/dataomnis/log/$(POD_NAME).log"
          {{- if eq .Values.resourcemanager.storage.background "s3" }}
          - name: RESOURCE_MANAGER_STORAGE_S3_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dataomnis-iaas-secret
                key: access_key_id
          - name: RESOURCE_MANAGER_STORAGE_S3_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dataomnis-iaas-secret
                key: secret_access_key
          {{- end }}
          {{- range $ename, $evalue := .Values.resourcemanager.envs }}
          - name: {{ $ename }}
            value: {{ $evalue | quote }}
          {{- end }}
        readinessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:{{ .Values.ports.resourcemanager }}"]
          {{- if .Values.resourcemanager.readinessProbe }}
          periodSeconds: {{ .Values.resourcemanager.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.resourcemanager.readinessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.readinessProbe.initialDelaySeconds }}
          {{- end }}
        livenessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:{{ .Values.ports.resourcemanager }}"]
          {{- if .Values.resourcemanager.livenessProbe }}
          periodSeconds: {{ .Values.resourcemanager.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.resourcemanager.livenessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.livenessProbe.initialDelaySeconds }}
          {{- end }}
        volumeMounts:
          - name: config
            mountPath: /opt/dataomnis/conf
            readOnly: true
          {{- if eq .Values.resourcemanager.storage.background "hdfs" }}
          - name: hdfs-config
            mountPath: {{ .Values.resourcemanager.storage.hadoopConfDir }}
            readOnly: true
          {{- end }}
          {{- if eq .Values.common.logOutput "file" }}
          - name: log
            mountPath: /opt/dataomnis/log
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: dataomnis-config
            items:
              - key: resourcemanager.yaml
                path: resourcemanager.yaml
        {{- if eq .Values.resourcemanager.storage.background "hdfs" }}
        - name: hdfs-config
          configMap:
            name: {{ .Values.hdfs.configmapName }}
            items:
              - key: core-site.xml
                path: core-site.xml
              - key: hdfs-site.xml
                path: hdfs-site.xml
        {{- end }}
        {{- if eq .Values.common.logOutput "file" }}
        - name: log
          hostPath:
            path: {{ .Values.persistent.hostPath }}/log/resourcemanager
            type: Directory
        {{- end  }}
        {{- if .Values.filebeat.enabled }}
        - name: filebeat-config
          configMap:
            name: filebeat-config
            items:
              - key: filebeat.yaml
                path: filebeat.yaml
        {{- end  }}
