apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dataomnis.fullname" . }}-spacemanager
  labels:
{{ include "dataomnis.labels" . | indent 4 }}
    component: spacemanager
annotations:
  {{- range $key, $value := .Values.spacemanager.annotations }}
  {{ $key | quote }}: {{ $value | quote }}
  {{- end }}
spec:
  replicas: {{ coalesce .Values.spacemanager.replicas .Values.common.replicas }}
  strategy:
    type: {{ coalesce .Values.spacemanager.strategy .Values.common.strategy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      component: spacemanager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        component: spacemanager
      annotations:
      {{- range $key, $value := .Values.spacemanager.podAnnotations }}
      {{ $key | quote }}: {{ $value | quote }}
      {{- end }}
    spec:
      {{- if .Values.image.pullSecret }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecret }}
      {{- end }}
      initContainers:
      - name: wait-mysql
        image: {{ .Values.image.registry }}/library/{{- .Values.image.busybox }}
        imagePullPolicy: IfNotPresent
        command: ['/bin/sh', '-c', '{{ include "mysql.waiting.cmd" . }}']
      containers:
      - name: spacemanager
        image: {{ .Values.image.registry }}/dataomnis/spacemanager:{{- .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["sh", "-c", "spacemanager start -c /opt/dataomnis/conf/spacemanager.yaml"]
        ports:
          - name: service
            containerPort: {{ .Values.ports.spacemanager }}
          - name: metrics
            containerPort: {{ .Values.metricsPorts.spacemanager }}
        env:
          - name: SPACE_MANAGER_MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.mysql.secretName }}
                key: root
          - name: SPACE_MANAGER_IAAS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: dataomnis-iaas-secret
                key: access_key_id
          - name: SPACE_MANAGER_IAAS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: dataomnis-iaas-secret
                key: secret_access_key
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: SPACE_MANAGER_LOG_FILE_PATH
            value: "/opt/dataomnis/log/$(POD_NAME).log"
{{ include "spacemanager.link.services" . | indent 10 }}
          {{- range $ename, $evalue := .Values.spacemanager.envs }}
          - name: {{ $ename }}
            value: {{ $evalue | quote }}
          {{- end }}
        readinessProbe:
          exec:
            command: ["grpc_health_probe", "-addr=:{{ .Values.ports.spacemanager }}"]
          {{- if .Values.spacemanager.readinessProbe }}
          periodSeconds: {{ .Values.spacemanager.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.spacemanager.readinessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.readinessProbe.initialDelaySeconds }}
          {{- end }}
        livenessProbe:
          exec:
            command: [ "grpc_health_probe", "-addr=:{{ .Values.ports.spacemanager }}" ]
          {{- if .Values.spacemanager.livenessProbe }}
          periodSeconds: {{ .Values.spacemanager.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.spacemanager.livenessProbe.initialDelaySeconds }}
          {{- else }}
          periodSeconds: {{ .Values.common.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.common.livenessProbe.initialDelaySeconds }}
          {{- end }}
        volumeMounts:
          - name: config
            mountPath: /opt/dataomnis/conf
            readOnly: true
          {{- if eq .Values.common.logOutput "file" }}
          - name: log
            mountPath: /opt/dataomnis/log
          {{- end }}
      volumes:
        - name: config
          configMap:
            name: dataomnis-config
            items:
              - key: spacemanager.yaml
                path: spacemanager.yaml
        {{- if eq .Values.common.logOutput "file" }}
        - name: log
          hostPath:
            path: {{ .Values.persistent.hostPath }}/log/spacemanager
            type: Directory
        {{- end  }}
