apiVersion: "etcd.database.coreos.com/v1beta2"
kind: "EtcdCluster"
metadata:
  name: {{ include "etcd-cluster.fullname" . }}
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  annotations:
    etcd.database.coreos.com/scope: clusterwide
spec:
  version: "{{ .Values.image.tag }}"
  repository: "{{ .Values.image.etcd }}"
  {{- if .Values.persistent.localPv.nodes }}
  size: {{ len .Values.persistent.localPv.nodes }}
  {{- else }}
  size: {{ .Values.replicaCount }}
  {{- end }}
  resources:
{{ toYaml .Values.resources | indent 4 }}
  pod:
    busyboxImage: {{ .Values.image.busyBox }}
    persistentVolumeClaimSpec:
      accessModes: {{ .Values.persistent.accessModes }}
      {{- if .Values.persistent.localPv.enable }}
      storageClassName: {{ include "etcd-cluster.fullname" . }}-sc
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistent.size }}
