{{ $fullname := include "etcd-cluster.fullname" . }}

{{- if .Values.persistent.localPv.enable }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ $fullname }}-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- range $node := .Values.persistent.localPv.nodes }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $fullname }}-{{ $node }}-pv
spec:
  capacity:
    storage: {{ $.Values.persistent.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: {{ $.Values.persistent.localPv.reclaimPolicy }}
  storageClassName: {{ $fullname }}-sc
  local:
    path: {{ $.Values.persistent.localPv.home }}/{{ $.Release.Name }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ $node }}
{{- end }}
{{- end }}