## FirstAtAll: create namenode / datanode / journalnode / zookeeper dir with: {{ .Values.hdfsHome }}/{{ .Release.Name }}/xxxxnode

fullnameOverride: ""

storageClass: ""

hdfsHome: /mnt

version: 2.9.2

image: dataworkbench/hadoop-test:2.9.2   #  dataworkbench/hdfs-metrics:3.1.0

namenode:
  nodePort: 30091
  webPort: 50070  # 3.x 9870 ; 2.x 50070
  nodes:
    - "worker-s001"
    - "worker-s002"
  storage:
    capacity: 10Gi
    reclaimPolicy: Retain

datanode:
  nodes:
    - "worker-s001"
    - "worker-s002"
    - "worker-s003"
  storage:
    capacity: 50Gi
    reclaimPolicy: Retain

journalnode:
  nodes:
    - "worker-s001"
    - "worker-s002"
    - "worker-s003"
  storage:
    capacity: 10Gi
    reclaimPolicy: Retain

zookeeper:
  quorum:
  nodes:
    - "worker-s001"
    - "worker-s002"
    - "worker-s003"
  storage:
    capacity: 1Gi
    reclaimPolicy: Retain

yarn:
  nmReplicas: ""  #  fill if you need to deploy yarn