apiVersion: v1
kind: Service
metadata:
  name: my-hdfs-http
  labels:
    app: hdfs-namenode
spec:
  ports:
    - port: 50070
      protocol: TCP
      targetPort: 50070
      nodePort: {{ .Values.namenodeNodePort }}
  type: NodePort
  selector:
    github.dataworkbench.com/statefulset-name: hdfs-namenode