# Default values for mysql-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

storageClassName: "managed-nfs-storage"
pxc:
  size: 3
  image: percona/percona-xtradb-cluster:8.0.19-10.1
  resources:
    requests:
      memory: 1G
      cpu: 600m
  storage: 2Gi
haproxy:
  enabled: true
  size: 3
  image: percona/percona-xtradb-cluster-operator:1.5.0-haproxy
  resources:
    requests:
      memory: 1G
      cpu: 600m
  storage: 2Gi
proxysql:
  enabled: false
  size: 3
  image: percona/percona-xtradb-cluster-operator:1.5.0-proxysql
  resources:
    requests:
      memory: 1G
      cpu: 600m
  storage: 2Gi
backup:
  image: percona/percona-xtradb-cluster-operator:1.9.0-pxc8.0-backup
  storage: 2Gi
  schedule:
    name: "daily-backup"
    schedule: "0 4 * * *"