# Default values for mysql-cluster.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
schedule: "0 4 * * *"
pxc:
  size: 3
  image: percona/percona-xtradb-cluster:8.0.19-10.1
  resources:
    requests:
      memory: 1G
      cpu: 600m
haproxy:
  enabled: true
  size: 3
  image: percona/percona-xtradb-cluster-operator:1.5.0-haproxy
  resources:
    requests:
      memory: 1G
      cpu: 600m

proxysql:
  enabled: false
  size: 3
  image: percona/percona-xtradb-cluster-operator:1.5.0-proxysql
  resources:
    requests:
      memory: 1G
      cpu: 600m

backup:
  image: percona/percona-xtradb-cluster-operator:1.5.0-pxc8.0-backup
  storageClassName: "managed-nfs-storage"
  accessModes: [ "ReadWriteOnce" ]
  storage: 2Gi