# Default values for redis-cluster.

sentinel:
  image: redis
  replicaCount: 3
  resource:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  config:
    - "down-after-milliseconds 2000"
    - "failover-timeout 3000"

redis:
  image: redis
  replicaCount: 3
  resource:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 1000m
      memory: 2048Mi
  config:
    - "maxclients 100"
    - "hz 50"
    - "timeout 60"
    - "tcp-keepalive 60"
    - "client-output-buffer-limit normal 0 0 0"
    - "client-output-buffer-limit slave 1000000000 1000000000 0"
    - "client-output-buffer-limit pubsub 33554432 8388608 60"
  persistent:
    enable: true
    size: 10Gi
    accessModes: ["ReadWriteOnce"]
    localPv:
      enable: true # if use local pv with hostPath
      home: /data/dataomnis
      reclaimPolicy: Retain
      nodes: # the length of nodes must be equal to replicaCount
        - worker-1
        - worker-2
        - worker-3
