
image:
  registry: docker.io
  pullPolicy: IfNotPresent
  pullSecrets: []
  redis: redis


redisCluster:
  masterSize: 3
  clusterReplicas: 1


persistent:
  enable: true
  size: 10Gi
  accessModes: ["ReadWriteOnce"]
  localPv:
    enable: true # if use local pv with hostPath
    home: /data/dataomnis
    reclaimPolicy: Retain
    nodes: # the length of nodes must be equal to clusterSize
      - worker-s001
      - worker-s002
      - worker-s003