# Default values for redis-cluster.

sentinel:
  image: dockerhub.dataomnis.io/spotahome/redis
  replicaCount: 3
  resource:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 1024Mi
  config:
    - "down-after-milliseconds 2000"
    - "failover-timeout 3000"

redis:
  image: dockerhub.dataomnis.io/spotahome/redis
  replicaCount: 3
  resource:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 4Gi
  config:
    - "maxclients 100"
    - "hz 50"
    - "timeout 60"
    - "tcp-keepalive 60"
    - "client-output-buffer-limit normal 0 0 0"
    - "client-output-buffer-limit slave 1000000000 1000000000 0"
    - "client-output-buffer-limit pubsub 33554432 8388608 60"
  persistent:
    enable: false
    size: 20Gi
    accessModes: ["ReadWriteOnce"]