{{- if not .Values.pxc.disableTLS }}
{{- if not .Values.pxc.certManager }}
{{ $ca := genCA (include "pxc-database.fullname" .) 365 }}
{{- if not (hasKey .Values.secrets.tls "cluster") }}
---
{{- $name := printf "%s-pxc" (include "pxc-database.fullname" .) }}
{{- $altNames := list ( printf "*.%s.%s" $name .Release.Namespace ) ( printf "*.%s.%s.svc" $name .Release.Namespace ) ( printf "*.%s.%s.svc.cluster.local" $name .Release.Namespace ) -}}
{{ $cert := genSignedCert $name nil $altNames 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pxc-database.fullname" . }}-ssl
  labels:
{{ include "pxc-database.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
{{- if not (hasKey .Values.secrets.tls "internal") }}
---
{{- $name := printf "%s-proxysql" (include "pxc-database.fullname" .) }}
{{- $altNames := list ( printf "*.%s.%s" $name .Release.Namespace ) ( printf "*.%s.%s.svc" $name .Release.Namespace ) ( printf "*.%s.%s.svc.cluster.local" $name .Release.Namespace ) -}}
{{ $cert := genSignedCert (include "pxc-database.fullname" .) nil nil 365 $ca }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pxc-database.fullname" . }}-ssl-internal
  labels:
{{ include "pxc-database.labels" . | indent 4 }}
type: kubernetes.io/tls
data:
  ca.crt: {{ $ca.Cert | b64enc }}
  tls.crt: {{ $cert.Cert | b64enc }}
  tls.key: {{ $cert.Key | b64enc }}
{{- end }}
{{- end }}
{{- end }}