apiVersion: etcd.database.coreos.com/v1beta2
kind: EtcdCluster
metadata:
  name: {{ .Release.Name }}
  ## Adding this annotation make this cluster managed by clusterwide operators
  ## namespaced operators ignore it
  annotations:
    etcd.database.coreos.com/scope: clusterwide
spec:
  size: {{ .Values.etcdCluster.replicas }}
  version: {{ .Values.etcdCluster.version }}
  pod:
    restartPolicy: Always
    persistentVolumeClaimSpec:
      storageClassName: {{ .Values.etcdCluster.storageClass }}
      accessModes:
        - {{ .Values.etcdCluster.accessModes }}
      resources:
        requests:
          storage: {{ .Values.etcdCluster.storage }}