apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: redis
spec:
  sentinel:
    image: {{ include "sentinel.image" . }}
    imagePullPolicy: IfNotPresent
    replicas: {{ .Values.sentinel.replicaCount }}
    resources:
{{ toYaml .Values.sentinel.resource | indent 6 }}
    customConfig:
{{ toYaml .Values.sentinel.config | indent 6 }}
  redis:
    image: {{ include "sentinel.image" . }}
    imagePullPolicy: IfNotPresent
    replicas: {{ .Values.redis.replicaCount }}
    resources:
{{ toYaml .Values.redis.resource | indent 6 }}
    customConfig:
{{ toYaml .Values.redis.config | indent 6 }}
    {{- if .Values.redis.persistent.enable }}
    storage:
      keepAfterDeletion: true
      persistentVolumeClaim:
        metadata:
          name: {{ include "redis-cluster.fullname" . }}-persistent
        spec:
          accessModes: {{ .Values.redis.persistent.accessModes }}
          resources:
            requests:
              storage: {{ .Values.redis.persistent.size }}
    {{- end }}
