{{- if .Values.storageClass }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-disks
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
{{- else }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: journalnode-disks
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jnpv-01
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: journalnode-disks
  local:
    path: /mnt/hdfs/jn
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.jn01Node }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jnpv-02
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: journalnode-disks
  local:
    path: /mnt/hdfs/jn
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.jn02Node }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jnpv-03
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: journalnode-disks
  local:
    path: /mnt/hdfs/jn
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.jn03Node }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: namenode-disks
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nnpv-01
spec:
  capacity:
    storage: {{ .Values.namenodeCapacity }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: namenode-disks
  local:
    path: /mnt/hdfs/nn
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.nn01Node }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nnpv-02
spec:
  capacity:
    storage: {{ .Values.namenodeCapacity }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: namenode-disks
  local:
    path: /mnt/hdfs/nn
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.nn02Node }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: zk-disks
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk01-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: zk-disks
  local:
    path: /mnt/hdfs/zk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.zk01Node }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk02-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: zk-disks
  local:
    path: /mnt/hdfs/zk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.zk02Node }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zk03-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: zk-disks
  local:
    path: /mnt/hdfs/zk
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - {{ .Values.zk03Node }}
{{- end }}