apiVersion: v1
kind: Service
metadata:
  name: my-hdfs-http
  labels:
    app: hdfs-namenode
    chart: hdfs-namenode-k8s-0.1.0
    release: my-hdfs-namenode
spec:
  ports:
    - port: 50070
      protocol: TCP
      targetPort: 50070
      nodePort: 30091
  type: NodePort
  selector:
    app: hdfs-namenode
    release: my-hdfs-namenode