apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hdfs-operator-manager-role
rules:
  - apiGroups:
      - qy.dataworkbench.com
    resources:
      - hdfs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - qy.dataworkbench.com
    resources:
      - hdfs/finalizers
    verbs:
      - update
  - apiGroups:
      - qy.dataworkbench.com
    resources:
      - hdfs/status
    verbs:
      - get
      - patch
      - update