# Default values for dataworkbench.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  pullPolicy: IfNotPresent
  dataworkbench: dataworkbench/dataworkbench:latest
  flyway: dataworkbench/flyway:latest


# serviceName: port
ports:
  opentracing: 6831
  apiserver: 9001
  spacemanager: 9101
  flowmanager: 9103
  scheduler: 9105
  sourcemanager: 9107
  jobmanager: 9109
  udfmanager: 9111
  jaeger: 9113
  mysql: 3306

## mysql settings
mysql:
  user: root
  password: zhu88jie
  database: data_workbench
  logLevel: 4

## etcd settings
etcd:
  dial_timeout: 5s

# common settings for all service
common:
  replicas: 3
  strategy: RollingUpdate
  logLevel: 1
  grpcLogLevel: 1
  grpcLogVerbosity: 99
  livenessProbe:
    initialDelaySeconds: 10
    periodSeconds: 15
  readinessProbe:
    periodSeconds: 10
    initialDelaySeconds: 20

# apiserver settings
apiserver:
  annotations: {}
  podAnnotations: {}
  service:
    type: ClusterIP
    annotations: {}
  envs:
    API_SERVER_READ_TIMEOUT: 30s
    API_SERVER_WRITE_TIMEOUT: 30s
    API_SERVER_DLE_TIMEOUT: 30s
    API_SERVER_EXIT_TIMEOUT: 5m
    API_SERVER_TRACER_SERVICE_NAME: apiserver

# spacemanager settings
spacemanager:
  annotations: {}
  podAnnotations: {}
  service:
    type: ClusterIP
    annotations: {}
  envs:
    SPACE_MANAGER_TRACER_SERVICE_NAME: spacemanager
    SPACE_MANAGER_MYSQL_USERS: root
    SPACE_MANAGER_MYSQL_DATABASE: data_workbench
    SPACE_MANAGER_MYSQL_LOG_LEVEL: 4
    SPACE_MANAGER_MYSQL_SLOW_THRESHOLD: 2s
    SPACE_MANAGER_MYSQL_CONN_MAX_LIFETIME: 10m
  metric:
    enabled: false
    address: "0.0.0.0:9201"
    urlPath: "/metrics"

# flowmanager settings
flowmanager:
  annotations: {}
  podAnnotations: {}
  service:
    type: ClusterIP
    annotations: {}
  envs:
    FLOW_MANAGER_TRACER_SERVICE_NAME: flowmanager
    FLOW_MANAGER_MYSQL_USERS: root
    FLOW_MANAGER_MYSQL_DATABASE: data_workbench
    FLOW_MANAGER_MYSQL_LOG_LEVEL: 4
    FLOW_MANAGER_MYSQL_SLOW_THRESHOLD: 2s
    FLOW_MANAGER_MYSQL_CONN_MAX_LIFETIME: 10m
  metric:
    enabled: false
    address: "0.0.0.0:9203"
    urlPath: "/metrics"
