apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "name" . | quote }}
  labels:
    app.kubernetes.io/component: app
{{ include "helm-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: app
{{ include "common-labels" . | indent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: app
{{ include "common-labels" . | indent 8 }}
{{- if .Values.podAnnotations }}
      annotations:
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
    spec:
    {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
    {{- end }}
{{- if .Values.rbac.install }}
      serviceAccountName: {{ include "name" . | quote }}
{{- end }}
      containers:
      - name: {{ include "name" . | quote }}
        image: {{ include "operator.image" . | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: 9710
          name: metrics
          protocol: TCP
