apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-cluster-operator.fullname" . }}
spec:
  replicas: {{ .Values.operator.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: {{ include "redis-cluster-operator.fullname" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/part-of: dataomnis
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: operator
        app.kubernetes.io/name: {{ include "redis-cluster-operator.fullname" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/part-of: dataomnis
    spec:
      serviceAccountName: {{ .Values.operator.service_account_name }}
      securityContext:
        {{- .Values.operator.podsecurityContext | toYaml | nindent 8 }}
      {{- if .Values.image.pullSecretName }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecretName }}
      {{- end }}
      containers:
        - name: {{ include "redis-cluster-operator.fullname" . }}
          # Replace this with the built image name
          image: {{ include "redis-cluster-operator.image" . }}
          securityContext:
            {{- .Values.operator.containersecurityContext | toYaml | nindent 12 }}
          command:
          - redis-cluster-operator
          args:
          - --rename-command-path=/etc/redisconf
          - --rename-command-file=redis.conf
          imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
          resources:
            {{- .Values.operator.resources | toYaml | nindent 12 }}
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Values.operator.namespace | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ include "redis-cluster-operator.fullname" . | quote }}
          volumeMounts:
            - name: redisconf
              mountPath: /etc/redisconf
      volumes:
        - name: redisconf
          configMap:
            name: redis-admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-admin
data:
  redis.conf: |- 
    {{- .Values.data.redis_conf | nindent 4 }}
