apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-cluster-operator.fullname" . }}
  labels:
{{ include "redis-cluster-operator.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
{{ include "redis-cluster-operator.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "redis-cluster-operator.labels" . | indent 8 }}
    spec:
      serviceAccountName: {{ .Values.service_account_name }}
      securityContext:
        {{- .Values.podsecurityContext | toYaml | nindent 8 }}
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.image.pullSecrets }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      containers:
        - name: {{ include "redis-cluster-operator.fullname" . }}
          # Replace this with the built image name
          image: {{ include "redis-cluster-operator.image" . }}
          securityContext:
            {{- .Values.containersecurityContext | toYaml | nindent 12 }}
          command:
          - redis-cluster-operator
          args:
          - --rename-command-path=/etc/redisconf
          - --rename-command-file=redis.conf
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          resources:
            {{- .Values.resources | toYaml | nindent 12 }}
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Values.namespace | quote }}
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: {{ include "redis-cluster-operator.fullname" . | quote }}
          volumeMounts:
            - name: redisconf
              mountPath: /etc/redisconf
      volumes:
        - name: redisconf
          configMap:
            name: redis-admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-admin
data:
  redis.conf: |- 
    {{- .Values.data.redis_conf | nindent 4 }}
