apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    component: redis
spec:
  sentinel:
    image: {{ include "sentinel.image" . }}
    imagePullPolicy: IfNotPresent
    {{- if .Values.redis.persistent.localPv.nodes }}
    replicas: {{ len .Values.redis.persistent.localPv.nodes }}
    {{- else }}
    replicas: {{ .Values.sentinel.replicaCount }}
    {{- end }}
    resources:
{{ toYaml .Values.sentinel.resource | indent 6 }}
    customConfig:
{{ toYaml .Values.sentinel.config | indent 6 }}
  redis:
    image: {{ include "sentinel.image" . }}
    imagePullPolicy: IfNotPresent
    replicas: {{ .Values.redis.replicaCount }}
    resources:
{{ toYaml .Values.redis.resource | indent 6 }}
    customConfig:
{{ toYaml .Values.redis.config | indent 6 }}
    {{- if .Values.redis.persistent.enable }}
    storage:
      keepAfterDeletion: true
      persistentVolumeClaim:
        metadata:
          name: {{ .Release.Name }}-persistent
        spec:
          accessModes: {{ .Values.redis.persistent.accessModes }}
          {{- if .Values.redis.persistent.localPv.enable }}
          storageClassName: {{ include "redis-cluster.fullname" . }}-sc
          {{- end }}
          resources:
            requests:
              storage: {{ .Values.redis.persistent.size }}
    {{- end }}
