apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  annotations:
    # if your operator run as cluster-scoped, add this annotations
    redis.kun/scope: cluster-scoped
  name: {{ include "redis-cluster.fullname" . }}
spec:
  masterSize: {{ .Values.masterSize }}
  clusterReplicas: {{ .Values.clusterReplicas }}
  image: {{ include "redis-cluster.image" . }}
  imagePullPolicy: {{ .Values.image.pullPolicy }}
  {{- if .Values.image.pullSecrets }}
  imagePullSecrets:
    {{- range .Values.image.pullSecrets }}
    - name: {{ . }}
    {{- end }}
  {{- end }}
  storage:
    type: persistent-claim
    size: {{ .Values.persistent.size }}
    class: {{ include "redis-cluster.fullname" . }}-sc
    deleteClaim: true
  config:
    logfile: "/data/redis.log"
    activerehashing: "yes"
    appendonly: "yes"
    list-compress-depth: "0"
    slowlog-log-slower-than: "10000"
    slowlog-max-len: "128"
    stop-writes-on-bgsave-error: "yes"
    tcp-keepalive: "0"
    timeout: "0"
