apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: hdfs-operator-controller-manager-metrics-service
spec:
  clusterIP: None
  ports:
    - name: https
      port: 8443
      protocol: TCP
      targetPort: https
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP

