apiVersion: pxc.percona.com/v1-9-0
kind: PerconaXtraDBCluster
metadata:
  name: cluster1
  finalizers:
    - delete-pxc-pods-in-order
spec:
  crVersion: 1.9.0
  secretsName: my-cluster-secrets
  vaultSecretName: keyring-secret-vault
  sslSecretName: my-cluster-ssl
  sslInternalSecretName: my-cluster-ssl-internal
  logCollectorSecretName: my-log-collector-secrets
  allowUnsafeConfigurations: false
  updateStrategy: Never
  upgradeOptions:
    versionServiceEndpoint: https://check.percona.com
    apply: 8.0-recommended
    schedule: "0 4 * * *"
  pxc:
    size: {{ .Values.pxc.size }}
    image: {{ .Values.pxc.image }}
    autoRecovery: true
    resources:
      requests:
        memory: {{ .Values.pxc.resources.requests.memory }}
        cpu: {{ .Values.pxc.resources.requests.cpu }}
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    podDisruptionBudget:
      maxUnavailable: 1
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: {{ .Values.storageClassName }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.pxc.storage }}
    gracePeriod: 600
  haproxy:
    enabled: {{ .Values.haproxy.enabled }}
    size: {{ .Values.haproxy.size }}
    image: {{ .Values.haproxy.image }}
    resources:
      requests:
        memory: {{ .Values.haproxy.resources.requests.memory }}
        cpu: {{ .Values.haproxy.resources.requests.cpu }}
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"

    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: {{ .Values.storageClassName }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.haproxy.storage }}
  proxysql:
    enabled: {{ .Values.proxysql.enabled }}
    size: {{ .Values.proxysql.size }}
    image: {{ .Values.proxysql.image }}
    resources:
      requests:
        memory: {{ .Values.proxysql.resources.requests.memory }}
        cpu: {{ .Values.proxysql.resources.requests.cpu }}
    affinity:
      antiAffinityTopologyKey: "kubernetes.io/hostname"
    volumeSpec:
      persistentVolumeClaim:
        storageClassName: {{ .Values.storageClassName }}
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.proxysql.storage }}
    podDisruptionBudget:
      maxUnavailable: 1
    gracePeriod: 30
  logcollector:
    enabled: true
    image: percona/percona-xtradb-cluster-operator:1.9.0-logcollector

  backup:
    image: {{ .Values.backup.image }}
    pitr:
      enabled: false
      storageName: STORAGE-NAME-HERE
      timeBetweenUploads: 60
    storages:
      fs-pvc:
        type: filesystem
        volume:
          persistentVolumeClaim:
            storageClassName: {{ .Values.storageClassName }}
            accessModes: [ "ReadWriteOnce" ]
            resources:
              requests:
                storage: {{ .Values.backup.storage }}
    schedule:
      - name: {{ .Values.backup.schedule.name }}
        schedule: {{ .Values.backup.schedule.schedule }}
        keep: 3
        storageName: fs-pvc