apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: engine-manager
    release: enginge-manager-release   # prometheus 通过该label 来发现该serviceMonitor
  name: engine-manager-service-monitor
  namespace: kubesphere-monitoring-system
spec:
  jobLabel: engine-exporter
  selector:
    matchLabels:
      component: enginemanager-service   # 该serviceMonitor 通过标签选择器 来自动发现exporter 的sevice
  namespaceSelector:
    any: true
  endpoints:
    - port: metrics    # service 端口
      interval: 30s
      honorLabels: true
